export const GET_AIRPORTS = 'GET_AIRPORTS';
export const ADD_ROUTE = 'ADD_ROUTE';
export const GET_SYSTEM_ANALYTICS = 'GET_SYSTEM_ANALYTICS';
export const CHANGE_SYSTEM_OPTION = 'CHANGE_SYSTEM_OPTION';