export const GET_MAIN_ANALYTICS = 'GET_MAIN_ANALYTICS';
export const GET_SYSTEM_ANALYTICS = 'GET_SYSTEM_ANALYTICS';
export const CHANGE_SYSTEM_OPTION = 'CHANGE_SYSTEM_OPTION';
export const GET_ADDITION_ANALYTICS= 'GET_ADDITION_ANALYTICS';
export const OPEN_ADDITION_ANALYTICS_LAYER= 'OPEN_ADDITION_ANALYTICS_LAYER';